import { useState } from "react";
import { X, FileText, Download, Printer, Check, ShieldCheck, DollarSign, ArrowRight, Lock, Server } from "lucide-react";

export default function ExecutiveBriefModal({
  open = false,
  onClose = () => {},
  repo = "",
  alternative = {},
  paidTool = {},
  trustScore = null,
}) {
  const [teamSize, setTeamSize] = useState(10);
  if (!open) return null;

  const annualSaaSPerUser = paidTool.pricePerYearUsd || 120;
  const annualSaaSTeam = annualSaaSPerUser * teamSize;
  const selfHostedAnnual = (alternative.tco?.hostingMonthlyEstimateUsd || 5) * 12;
  const annualSavings = Math.max(0, annualSaaSTeam - selfHostedAnnual);
  const threeYearSavings = annualSavings * 3;

  const scoreNum = trustScore?.score || 85;
  const parityList = alternative.parity || ["Core workspace", "Data sovereignty", "API access"];
  const gapsList = alternative.gaps || ["Minor edge integrations"];

  const generateMarkdown = () => {
    return `# Executive Migration Brief: ${paidTool.name || "Proprietary SaaS"} → ${alternative.name || "Open Source"}

**Generated:** ${new Date().toISOString().split("T")[0]}
**Target Open-Source Solution:** [${alternative.name || repo}](https://github.com/${repo})
**Replaces:** ${paidTool.name || "Proprietary SaaS"} (${paidTool.category || "General"})

---

## 1. Financial Impact & ROI (Team of ${teamSize})
- **Proprietary SaaS Annual Cost:** $${annualSaaSTeam.toLocaleString()}/yr ($${annualSaaSPerUser}/user/yr)
- **Self-Hosted Infrastructure TCO:** $${selfHostedAnnual.toLocaleString()}/yr (~$${(selfHostedAnnual / 12).toFixed(0)}/mo)
- **Net Annual Team Savings:** **$${annualSavings.toLocaleString()}/year**
- **3-Year Projected ROI:** **$${threeYearSavings.toLocaleString()} Saved**

## 2. Security, License & Compliance
- **SPDX License:** ${alternative.license?.spdx || "MIT"} (${alternative.license?.type || "Permissive"})
- **Trust & Health Score:** ${scoreNum}/100 (Strong Governance & Maintenance)
- **Data Sovereignty:** 100% Local-First / Self-Hosted (Zero Cloud Vendor Lock-in)

## 3. Feature Parity & Coverage
### ✅ Supported Features
${parityList.map((p) => `- ${p}`).join("\n")}

### ⚠️ Known Trade-Offs & Gaps
${gapsList.map((g) => `- ${g}`).join("\n")}

## 4. Migration Strategy
${alternative.migrationNotes || "Export data to standard JSON/CSV and import into self-hosted instance."}

---
*Report generated by OpenSource Hub — Zero-telemetry, local-first open-source intelligence.*
`;
  };

  const handleDownloadMd = () => {
    const md = generateMarkdown();
    const blob = new Blob([md], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `Executive_Brief_${(alternative.name || "tool").replace(/\s+/g, "_")}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div
      role="dialog"
      aria-modal="true"
      aria-labelledby="brief-modal-title"
      className="fixed inset-0 z-50 grid place-items-center bg-black/60 backdrop-blur-sm p-4 overflow-y-auto animate-fade-in"
      onClick={onClose}
    >
      <div
        className="card-elevated max-w-2xl w-full p-6 sm:p-8 space-y-6 bg-surface text-ink border border-line shadow-2xl rounded-3xl max-h-[90vh] overflow-y-auto print:max-h-none print:shadow-none print:border-none print:p-0"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div className="flex items-center justify-between border-b border-line pb-4 print:hidden">
          <div className="flex items-center gap-2.5">
            <div className="size-10 rounded-xl bg-ink text-surface dark:bg-surface dark:text-ink grid place-items-center shrink-0">
              <FileText size={20} className="text-accent" />
            </div>
            <div>
              <h2 id="brief-modal-title" className="font-display text-lg sm:text-xl font-bold text-ink">
                Executive Migration Brief
              </h2>
              <p className="text-xs text-dim">
                CTO &amp; Engineering Decision Report for {alternative.name}
              </p>
            </div>
          </div>

          <button
            type="button"
            onClick={onClose}
            aria-label="Close dialog"
            className="p-1 rounded-lg text-faint hover:text-ink hover:bg-elevated border border-line cursor-pointer"
          >
            <X size={18} />
          </button>
        </div>

        {/* Printable Title Block */}
        <div className="space-y-1">
          <span className="px-2.5 py-0.5 rounded-full bg-accent/10 border border-accent/20 text-accent font-semibold text-xs">
            Open-Source Migration Analysis
          </span>
          <h1 className="font-display text-2xl sm:text-3xl font-bold text-ink pt-1">
            {paidTool.name || "SaaS"} → {alternative.name || "Open-Source"}
          </h1>
          <p className="text-xs text-dim">
            Repository: <span className="font-mono text-ink">{repo}</span> · License:{" "}
            <span className="font-semibold text-ink">{alternative.license?.spdx || "MIT"}</span>
          </p>
        </div>

        {/* Financial ROI Calculator Box */}
        <div className="p-5 rounded-2xl bg-elevated/60 border border-line space-y-4">
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 border-b border-line/60 pb-3">
            <span className="font-semibold text-xs sm:text-sm text-ink flex items-center gap-1.5">
              <DollarSign size={16} className="text-trust" />
              <span>Projected Team Cost Comparison</span>
            </span>

            <div className="flex items-center gap-2 text-xs print:hidden">
              <span className="text-dim">Team Seats:</span>
              {[5, 10, 25, 50].map((sz) => (
                <button
                  key={sz}
                  type="button"
                  onClick={() => setTeamSize(sz)}
                  className={`px-2.5 py-1 rounded-lg text-xs font-semibold border cursor-pointer ${
                    teamSize === sz
                      ? "bg-ink text-surface dark:bg-surface dark:text-ink border-transparent"
                      : "border-line bg-surface text-dim hover:text-ink"
                  }`}
                >
                  {sz}
                </button>
              ))}
            </div>
          </div>

          <div className="grid grid-cols-2 sm:grid-cols-3 gap-3 text-center">
            <div className="p-3 rounded-xl bg-surface border border-line space-y-0.5">
              <span className="text-[11px] text-faint uppercase tracking-wider block">Proprietary SaaS</span>
              <span className="font-display text-base sm:text-lg font-bold text-caution tnum">
                ${annualSaaSTeam.toLocaleString()}/yr
              </span>
            </div>
            <div className="p-3 rounded-xl bg-surface border border-line space-y-0.5">
              <span className="text-[11px] text-faint uppercase tracking-wider block">Self-Hosted VPS</span>
              <span className="font-display text-base sm:text-lg font-bold text-ink tnum">
                ${selfHostedAnnual.toLocaleString()}/yr
              </span>
            </div>
            <div className="p-3 rounded-xl bg-trust/10 border border-trust/30 text-trust space-y-0.5 col-span-2 sm:col-span-1">
              <span className="text-[11px] font-bold uppercase tracking-wider block">Annual Savings</span>
              <span className="font-display text-base sm:text-lg font-bold text-trust tnum">
                +${annualSavings.toLocaleString()}/yr
              </span>
            </div>
          </div>

          <p className="text-[11px] text-dim text-center">
            Estimated 3-Year Cumulative Savings:{" "}
            <strong className="text-trust">${threeYearSavings.toLocaleString()}</strong>
          </p>
        </div>

        {/* Security & Governance Grid */}
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 text-xs">
          <div className="p-4 rounded-xl bg-surface border border-line space-y-2">
            <div className="flex items-center gap-2 font-semibold text-ink">
              <ShieldCheck size={16} className="text-trust" />
              <span>Security &amp; Health Score</span>
            </div>
            <div className="flex items-baseline gap-2">
              <span className="font-display text-2xl font-bold text-trust tnum">{scoreNum}/100</span>
              <span className="text-faint text-[11px]">Strong Governance &amp; Velocity</span>
            </div>
            <p className="text-[11.5px] text-dim">
              Verified active maintainer velocity, zero red-flag anomalies, and OSI-compliant licensing.
            </p>
          </div>

          <div className="p-4 rounded-xl bg-surface border border-line space-y-2">
            <div className="flex items-center gap-2 font-semibold text-ink">
              <Lock size={16} className="text-accent" />
              <span>Data Sovereignty</span>
            </div>
            <span className="inline-block px-2 py-0.5 rounded-full bg-trust/10 text-trust text-[10.5px] font-semibold">
              100% On-Premise / Air-Gapped Ready
            </span>
            <p className="text-[11.5px] text-dim">
              Full control over user data, backups, and GDPR/HIPAA compliance with zero third-party telemetry.
            </p>
          </div>
        </div>

        {/* Feature Parity & Trade-offs */}
        <div className="space-y-3 text-xs">
          <h3 className="font-bold text-ink">Feature Parity &amp; Gaps Assessment</h3>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
            <div className="p-3.5 rounded-xl bg-surface border border-line space-y-2">
              <span className="font-semibold text-trust flex items-center gap-1.5">
                <Check size={14} /> Full Feature Parity
              </span>
              <ul className="space-y-1 text-dim text-[11.5px]">
                {parityList.map((p, i) => (
                  <li key={i}>• {p}</li>
                ))}
              </ul>
            </div>

            <div className="p-3.5 rounded-xl bg-surface border border-line space-y-2">
              <span className="font-semibold text-caution flex items-center gap-1.5">
                <span>⚠️</span> Identified Trade-Offs
              </span>
              <ul className="space-y-1 text-dim text-[11.5px]">
                {gapsList.map((g, i) => (
                  <li key={i}>• {g}</li>
                ))}
              </ul>
            </div>
          </div>
        </div>

        {/* Action Buttons */}
        <div className="flex flex-col sm:flex-row items-center justify-between gap-3 pt-4 border-t border-line print:hidden">
          <span className="text-[11px] text-faint">
            Ready to export for your team's decision document
          </span>

          <div className="flex items-center gap-2 w-full sm:w-auto">
            <button
              type="button"
              onClick={handlePrint}
              className="btn-tactile flex-1 sm:flex-initial px-3.5 py-2 rounded-xl border border-line bg-surface hover:bg-elevated text-ink text-xs font-semibold inline-flex items-center justify-center gap-1.5 cursor-pointer"
            >
              <Printer size={14} />
              <span>Print / PDF</span>
            </button>
            <button
              type="button"
              onClick={handleDownloadMd}
              className="btn-tactile flex-1 sm:flex-initial px-4 py-2 rounded-xl bg-ink text-surface dark:bg-surface dark:text-ink text-xs font-semibold inline-flex items-center justify-center gap-1.5 shadow-sm hover:opacity-90 cursor-pointer"
            >
              <Download size={14} />
              <span>Download Markdown</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
