import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const catalogPath = path.join(__dirname, "..", "src", "data", "alternatives.json");

const newPairings = [
  {
    paidTool: {
      name: "ChatGPT Plus",
      slug: "chatgpt-plus",
      category: "AI & Machine Learning",
      pricePerYearUsd: 240,
      planName: "Plus",
    },
    alternative: {
      name: "Ollama",
      repo: "ollama/ollama",
      language: "Go",
      tags: ["ai", "llm", "local-first", "self-host", "gpu"],
      description: "Get up and running with Llama 3, Mistral, Gemma, and custom local models locally on macOS, Linux, and Windows.",
      parity: ["Local model inference", "OpenAI-compatible REST API", "GPU acceleration (Metal/CUDA/ROCm)", "Modelfile customization"],
      gaps: ["Requires local RAM / VRAM", "No hosted web UI included out of the box"],
      migrationNotes: "Point your OpenAI client baseURL to http://localhost:11434/v1 and pass model: 'llama3'.",
      platforms: ["mac", "linux", "win", "self-host"],
      license: { spdx: "MIT", type: "permissive" },
      demoUrl: "https://ollama.com",
      ecosystems: { docker: "ollama/ollama" },
      screenshots: [{ src: "https://ollama.com/public/ollama.png", alt: "Ollama interface" }],
      tco: { hostingMonthlyEstimateUsd: 0 },
    },
    relationship: "direct",
    goalTags: ["replace-chatgpt-plus", "local-ai", "privacy-llm"],
    verification: {
      apiCheckedAt: new Date().toISOString(),
      githubStars: 105000,
      githubLicense: "MIT",
      lastPushAt: new Date().toISOString(),
      source: "https://github.com/ollama/ollama",
    },
  },
  {
    paidTool: {
      name: "ChatGPT Team",
      slug: "chatgpt-team",
      category: "AI & Machine Learning",
      pricePerYearUsd: 300,
      planName: "Team",
    },
    alternative: {
      name: "Open WebUI",
      repo: "open-webui/open-webui",
      language: "Python",
      tags: ["ai", "chatgpt-ui", "local-first", "self-host", "rag"],
      description: "User-friendly AI interface for LLMs supporting Ollama, OpenAI-compatible APIs, RAG, Web Search, and multi-user RBAC.",
      parity: ["Full ChatGPT-style UI", "Document RAG & PDF chat", "Web search integration", "Multi-user authentication & roles"],
      gaps: ["Requires self-hosting backend (e.g. Ollama or API keys)"],
      migrationNotes: "Import conversation history and connect to your Ollama or OpenAI endpoint.",
      platforms: ["docker", "self-host", "web"],
      license: { spdx: "MIT", type: "permissive" },
      demoUrl: "https://openwebui.com",
      ecosystems: { docker: "ghcr.io/open-webui/open-webui:main" },
      screenshots: [{ src: "https://openwebui.com/logo.png", alt: "Open WebUI" }],
      tco: { hostingMonthlyEstimateUsd: 5 },
    },
    relationship: "direct",
    goalTags: ["replace-chatgpt-team", "ai-workspace"],
    verification: {
      apiCheckedAt: new Date().toISOString(),
      githubStars: 68000,
      githubLicense: "MIT",
      lastPushAt: new Date().toISOString(),
      source: "https://github.com/open-webui/open-webui",
    },
  },
  {
    paidTool: {
      name: "Pinecone",
      slug: "pinecone",
      category: "Databases & Search",
      pricePerYearUsd: 840,
      planName: "Standard",
    },
    alternative: {
      name: "Qdrant",
      repo: "qdrant/qdrant",
      language: "Rust",
      tags: ["vector-db", "similarity-search", "embeddings", "rust", "self-host"],
      description: "Vector search engine and database written in Rust for next-generation AI applications with payload filtering.",
      parity: ["Sub-millisecond HNSW vector search", "Complex payload filtering", "gRPC & REST API", "Quantization & SIMD acceleration"],
      gaps: ["Managed multi-region cloud requires enterprise contract"],
      migrationNotes: "Use Qdrant client for Python/TS; batch upload embeddings with collection schemas.",
      platforms: ["linux", "docker", "self-host"],
      license: { spdx: "Apache-2.0", type: "permissive" },
      demoUrl: "https://qdrant.tech",
      ecosystems: { docker: "qdrant/qdrant" },
      screenshots: [{ src: "https://qdrant.tech/images/logo.png", alt: "Qdrant Vector DB" }],
      tco: { hostingMonthlyEstimateUsd: 10 },
    },
    relationship: "direct",
    goalTags: ["replace-pinecone", "vector-database", "ai-search"],
    verification: {
      apiCheckedAt: new Date().toISOString(),
      githubStars: 23000,
      githubLicense: "Apache-2.0",
      lastPushAt: new Date().toISOString(),
      source: "https://github.com/qdrant/qdrant",
    },
  },
  {
    paidTool: {
      name: "ChromaDB Cloud",
      slug: "chromadb-cloud",
      category: "Databases & Search",
      pricePerYearUsd: 600,
      planName: "Pro",
    },
    alternative: {
      name: "Chroma",
      repo: "chroma-core/chroma",
      language: "Python",
      tags: ["vector-db", "ai", "embeddings", "python", "self-host"],
      description: "The AI-native open-source embedding database. Simple, developer-friendly vector search for LLM apps.",
      parity: ["Built-in embedding functions", "Filtering & metadata search", "Python & JavaScript SDKs", "Local & client-server mode"],
      gaps: ["Single-node horizontal scaling requires distributed orchestration"],
      migrationNotes: "Import collections with chromadb.Client() and run persist().",
      platforms: ["docker", "self-host", "python"],
      license: { spdx: "Apache-2.0", type: "permissive" },
      demoUrl: "https://trychroma.com",
      ecosystems: { docker: "chromadb/chroma" },
      screenshots: [{ src: "https://trychroma.com/logo.png", alt: "Chroma" }],
      tco: { hostingMonthlyEstimateUsd: 5 },
    },
    relationship: "direct",
    goalTags: ["replace-chromadb-cloud", "vector-database"],
    verification: {
      apiCheckedAt: new Date().toISOString(),
      githubStars: 19000,
      githubLicense: "Apache-2.0",
      lastPushAt: new Date().toISOString(),
      source: "https://github.com/chroma-core/chroma",
    },
  },
  {
    paidTool: {
      name: "Heroku",
      slug: "heroku",
      category: "DevOps & Cloud",
      pricePerYearUsd: 300,
      planName: "Standard Dynos",
    },
    alternative: {
      name: "Coolify",
      repo: "coollabsio/coolify",
      language: "PHP",
      tags: ["paas", "self-host", "docker", "deployments", "devops"],
      description: "An open-source & self-hostable Heroku / Netlify / Vercel alternative. Deploy apps, databases, and services anywhere.",
      parity: ["Git push to deploy", "Automatic SSL via Let's Encrypt", "Database management (Postgres, Redis, MySQL, Mongo)", "Multi-server support"],
      gaps: ["Requires self-managing VPS security"],
      migrationNotes: "Connect your GitHub account and select repo. Coolify auto-detects Dockerfile, Nixpacks, or Heroku buildpacks.",
      platforms: ["linux", "self-host", "docker"],
      license: { spdx: "Apache-2.0", type: "permissive" },
      demoUrl: "https://coolify.io",
      ecosystems: { docker: "ghcr.io/coollabsio/coolify:latest" },
      screenshots: [{ src: "https://coolify.io/docs/images/coolify.png", alt: "Coolify Dashboard" }],
      tco: { hostingMonthlyEstimateUsd: 6 },
    },
    relationship: "direct",
    goalTags: ["replace-heroku", "self-hosted-paas", "cloud-savings"],
    verification: {
      apiCheckedAt: new Date().toISOString(),
      githubStars: 39000,
      githubLicense: "Apache-2.0",
      lastPushAt: new Date().toISOString(),
      source: "https://github.com/coollabsio/coolify",
    },
  },
  {
    paidTool: {
      name: "Pingdom",
      slug: "pingdom",
      category: "Monitoring & Observability",
      pricePerYearUsd: 360,
      planName: "Synthetic Monitoring",
    },
    alternative: {
      name: "Uptime Kuma",
      repo: "louislam/uptime-kuma",
      language: "JavaScript",
      tags: ["uptime", "monitoring", "status-page", "self-host", "local-first"],
      description: "A fancy self-hosted monitoring tool with beautiful UI, status pages, and 90+ notification services.",
      parity: ["HTTP(s) / TCP / Ping / DNS / Docker container monitoring", "Custom public status pages", "Telegram, Discord, Slack, Email alerts", "Certificate expiry notifications"],
      gaps: ["No global multi-region probe network out of the box"],
      migrationNotes: "Export monitors as JSON and import directly into Uptime Kuma settings.",
      platforms: ["docker", "self-host", "linux", "win", "mac"],
      license: { spdx: "MIT", type: "permissive" },
      demoUrl: "https://uptime.kuma.pet",
      ecosystems: { docker: "louislam/uptime-kuma:1" },
      screenshots: [{ src: "https://uptime.kuma.pet/img/preview.png", alt: "Uptime Kuma preview" }],
      tco: { hostingMonthlyEstimateUsd: 3 },
    },
    relationship: "direct",
    goalTags: ["replace-pingdom", "uptime-monitoring", "status-pages"],
    verification: {
      apiCheckedAt: new Date().toISOString(),
      githubStars: 64000,
      githubLicense: "MIT",
      lastPushAt: new Date().toISOString(),
      source: "https://github.com/louislam/uptime-kuma",
    },
  },
  {
    paidTool: {
      name: "Datadog Infrastructure",
      slug: "datadog",
      category: "Monitoring & Observability",
      pricePerYearUsd: 1800,
      planName: "Pro (10 hosts)",
    },
    alternative: {
      name: "Netdata",
      repo: "netdata/netdata",
      language: "C",
      tags: ["monitoring", "metrics", "observability", "realtime", "c"],
      description: "Real-time performance and health monitoring for systems, hardware, containers, and applications with 1-second granularity.",
      parity: ["1-second metric resolution", "Zero-config auto-detection of 800+ services", "Low CPU/RAM footprint (~1% CPU)", "Anomaly detection ML"],
      gaps: ["Distributed APM tracing requires Jaeger or OpenTelemetry integration"],
      migrationNotes: "Install agent with 1-line bash script; Netdata auto-discovers all local services immediately.",
      platforms: ["linux", "docker", "self-host", "mac", "win"],
      license: { spdx: "GPL-3.0", type: "copyleft" },
      demoUrl: "https://www.netdata.cloud",
      ecosystems: { docker: "netdata/netdata" },
      screenshots: [{ src: "https://www.netdata.cloud/images/netdata-chart.png", alt: "Netdata metrics" }],
      tco: { hostingMonthlyEstimateUsd: 0 },
    },
    relationship: "direct",
    goalTags: ["replace-datadog", "system-monitoring", "server-metrics"],
    verification: {
      apiCheckedAt: new Date().toISOString(),
      githubStars: 72000,
      githubLicense: "GPL-3.0",
      lastPushAt: new Date().toISOString(),
      source: "https://github.com/netdata/netdata",
    },
  },
  {
    paidTool: {
      name: "Okta Customer Identity",
      slug: "okta",
      category: "Security & Identity",
      pricePerYearUsd: 1200,
      planName: "Workforce",
    },
    alternative: {
      name: "Authentik",
      repo: "goauthentik/authentik",
      language: "Python",
      tags: ["sso", "identity", "oauth2", "saml", "mfa", "self-host"],
      description: "An open-source Identity Provider focused on flexibility and versatility. Single sign-on, MFA, OAuth2/OIDC, SAML, and LDAP proxy.",
      parity: ["OAuth2 / OIDC / SAML 2.0 Provider", "Multi-factor authentication (WebAuthn, Passkeys, TOTP, Duo)", "User directory & LDAP outpost", "Custom execution flows & policies"],
      gaps: ["Smaller enterprise legacy connector catalog than Okta"],
      migrationNotes: "Import users via CSV/LDAP sync; configure OIDC applications with client ID/secrets.",
      platforms: ["docker", "k8s", "self-host", "linux"],
      license: { spdx: "GPL-3.0", type: "copyleft" },
      demoUrl: "https://goauthentik.io",
      ecosystems: { docker: "ghcr.io/goauthentik/server" },
      screenshots: [{ src: "https://goauthentik.io/img/flow.png", alt: "Authentik auth flow" }],
      tco: { hostingMonthlyEstimateUsd: 10 },
    },
    relationship: "direct",
    goalTags: ["replace-okta", "single-sign-on", "identity-provider"],
    verification: {
      apiCheckedAt: new Date().toISOString(),
      githubStars: 14000,
      githubLicense: "GPL-3.0",
      lastPushAt: new Date().toISOString(),
      source: "https://github.com/goauthentik/authentik",
    },
  },
  {
    paidTool: {
      name: "Auth0",
      slug: "auth0",
      category: "Security & Identity",
      pricePerYearUsd: 840,
      planName: "B2C Essential",
    },
    alternative: {
      name: "Keycloak",
      repo: "keycloak/keycloak",
      language: "Java",
      tags: ["auth", "identity", "saml", "oidc", "sso", "enterprise"],
      description: "Open Source Identity and Access Management for modern applications and services backed by Red Hat and CNCF.",
      parity: ["Single Sign-On (SSO)", "OpenID Connect & SAML 2.0", "Identity Brokering & Social Login", "User Federation with LDAP/Active Directory"],
      gaps: ["Heavier memory footprint (JVM based)"],
      migrationNotes: "Export realm JSON configuration and import into Keycloak instance.",
      platforms: ["docker", "k8s", "self-host", "linux", "win"],
      license: { spdx: "Apache-2.0", type: "permissive" },
      demoUrl: "https://www.keycloak.org",
      ecosystems: { docker: "quay.io/keycloak/keycloak" },
      screenshots: [{ src: "https://www.keycloak.org/resources/images/keycloak_logo.png", alt: "Keycloak" }],
      tco: { hostingMonthlyEstimateUsd: 15 },
    },
    relationship: "direct",
    goalTags: ["replace-auth0", "iam-enterprise", "user-management"],
    verification: {
      apiCheckedAt: new Date().toISOString(),
      githubStars: 25000,
      githubLicense: "Apache-2.0",
      lastPushAt: new Date().toISOString(),
      source: "https://github.com/keycloak/keycloak",
    },
  },
  {
    paidTool: {
      name: "CyberArk / BeyondTrust",
      slug: "cyberark",
      category: "Security & Infrastructure",
      pricePerYearUsd: 2400,
      planName: "Privileged Access",
    },
    alternative: {
      name: "Teleport",
      repo: "gravitational/teleport",
      language: "Go",
      tags: ["pam", "ssh", "kubernetes", "zero-trust", "audit", "security"],
      description: "Identity-native Infrastructure Access Management for SSH, Kubernetes clusters, databases, web applications, and Windows desktops.",
      parity: ["Certificate-based zero-trust access", "Full session recording and live audit replay", "Access requests with Slack/PagerDuty approvals", "Single sign-on integration"],
      gaps: ["Full enterprise RBAC features require Teleport Enterprise"],
      migrationNotes: "Deploy teleport auth and proxy service; install tsh CLI client on developer machines.",
      platforms: ["linux", "mac", "win", "docker", "k8s", "self-host"],
      license: { spdx: "AGPL-3.0", type: "copyleft" },
      demoUrl: "https://goteleport.com",
      ecosystems: { docker: "public.ecr.aws/gravitational/teleport" },
      screenshots: [{ src: "https://goteleport.com/static/og-image.png", alt: "Teleport" }],
      tco: { hostingMonthlyEstimateUsd: 20 },
    },
    relationship: "direct",
    goalTags: ["replace-cyberark", "zero-trust-ssh", "kubernetes-access"],
    verification: {
      apiCheckedAt: new Date().toISOString(),
      githubStars: 17000,
      githubLicense: "AGPL-3.0",
      lastPushAt: new Date().toISOString(),
      source: "https://github.com/gravitational/teleport",
    },
  },
  {
    paidTool: {
      name: "Adobe Photoshop",
      slug: "photoshop",
      category: "Creative & Design",
      pricePerYearUsd: 264,
      planName: "Single App",
    },
    alternative: {
      name: "Krita",
      repo: "KDE/krita",
      language: "C++",
      tags: ["digital-art", "painting", "illustration", "creative", "desktop"],
      description: "Krita is a professional free and open source painting program made by artists for artists. Full CMYK, HDR, PSD support.",
      parity: ["Brush stabilization & custom brush engines", "Layer management & blend modes", "PSD file format compatibility", "Drawing tablet pressure support"],
      gaps: ["No cloud-based generative AI firefly fill"],
      migrationNotes: "Open existing PSD files directly in Krita; export to PNG/JPG/TIFF.",
      platforms: ["win", "mac", "linux"],
      license: { spdx: "GPL-3.0", type: "copyleft" },
      demoUrl: "https://krita.org",
      ecosystems: {},
      screenshots: [{ src: "https://krita.org/images/krita-screenshot.png", alt: "Krita" }],
      tco: { hostingMonthlyEstimateUsd: 0 },
    },
    relationship: "direct",
    goalTags: ["replace-photoshop", "digital-art", "creative-suite"],
    verification: {
      apiCheckedAt: new Date().toISOString(),
      githubStars: 7000,
      githubLicense: "GPL-3.0",
      lastPushAt: new Date().toISOString(),
      source: "https://github.com/KDE/krita",
    },
  },
  {
    paidTool: {
      name: "Adobe Illustrator",
      slug: "illustrator",
      category: "Creative & Design",
      pricePerYearUsd: 264,
      planName: "Single App",
    },
    alternative: {
      name: "Inkscape",
      repo: "inkscape/inkscape",
      language: "C++",
      tags: ["vector", "svg", "illustration", "design", "desktop"],
      description: "Inkscape is a professional vector graphics editor for Linux, Windows and macOS. Free, open-source, and native W3C SVG compliant.",
      parity: ["Full SVG specification support", "Bezier curve and node editing", "Object creation, grouping, and transformations", "AI / EPS / PDF import and export"],
      gaps: ["Performance on massive files with 10k+ complex nodes"],
      migrationNotes: "Import AI/EPS vector files directly and save as clean SVG.",
      platforms: ["win", "mac", "linux"],
      license: { spdx: "GPL-3.0", type: "copyleft" },
      demoUrl: "https://inkscape.org",
      ecosystems: {},
      screenshots: [{ src: "https://inkscape.org/static/images/logo.png", alt: "Inkscape" }],
      tco: { hostingMonthlyEstimateUsd: 0 },
    },
    relationship: "direct",
    goalTags: ["replace-illustrator", "vector-editor", "svg-graphics"],
    verification: {
      apiCheckedAt: new Date().toISOString(),
      githubStars: 6000,
      githubLicense: "GPL-3.0",
      lastPushAt: new Date().toISOString(),
      source: "https://github.com/inkscape/inkscape",
    },
  },
  {
    paidTool: {
      name: "Autodesk Maya / 3ds Max",
      slug: "autodesk-maya",
      category: "3D & Animation",
      pricePerYearUsd: 1875,
      planName: "Commercial Seat",
    },
    alternative: {
      name: "Blender",
      repo: "blender/blender",
      language: "C++",
      tags: ["3d", "animation", "vfx", "rendering", "sculpting", "python"],
      description: "The free and open source 3D creation suite. Supports modeling, rigging, animation, simulation, rendering, compositing and motion tracking.",
      parity: ["Cycles & EEVEE photo-real rendering", "Complete sculpting and geometry nodes system", "Python scripting API", "Industry standard USD & glTF export"],
      gaps: ["Certain niche Hollywood legacy plugin bridges"],
      migrationNotes: "Import FBX/OBJ/USD assets directly into Blender 4.x viewport.",
      platforms: ["win", "mac", "linux"],
      license: { spdx: "GPL-2.0", type: "copyleft" },
      demoUrl: "https://www.blender.org",
      ecosystems: {},
      screenshots: [{ src: "https://www.blender.org/wp-content/themes/bthree/assets/images/blender-logo-white.svg", alt: "Blender 3D" }],
      tco: { hostingMonthlyEstimateUsd: 0 },
    },
    relationship: "direct",
    goalTags: ["replace-autodesk-maya", "3d-modeling", "vfx-rendering"],
    verification: {
      apiCheckedAt: new Date().toISOString(),
      githubStars: 15000,
      githubLicense: "GPL-2.0",
      lastPushAt: new Date().toISOString(),
      source: "https://github.com/blender/blender",
    },
  },
  {
    paidTool: {
      name: "Google Photos / iCloud+",
      slug: "google-photos",
      category: "Photos & Cloud Storage",
      pricePerYearUsd: 120,
      planName: "2TB Tier",
    },
    alternative: {
      name: "Immich",
      repo: "immich-app/immich",
      language: "TypeScript",
      tags: ["photos", "self-host", "ai-search", "facial-recognition", "mobile"],
      description: "High performance self-hosted photo and video management solution with facial recognition, object detection, and mobile backup.",
      parity: ["Automatic background mobile photo backup (iOS/Android)", "On-device / local facial recognition & machine learning search", "RAW file & Live Photo support", "Shared albums & partner sharing"],
      gaps: ["Requires self-managed disk storage & backups"],
      migrationNotes: "Use the Immich CLI to bulk-upload your existing Google Takeout zip archive.",
      platforms: ["docker", "self-host", "mobile", "web"],
      license: { spdx: "AGPL-3.0", type: "copyleft" },
      demoUrl: "https://immich.app",
      ecosystems: { docker: "ghcr.io/immich-app/immich-server:release" },
      screenshots: [{ src: "https://immich.app/img/immich-logo.svg", alt: "Immich" }],
      tco: { hostingMonthlyEstimateUsd: 5 },
    },
    relationship: "direct",
    goalTags: ["replace-google-photos", "photo-backup", "self-hosted-media"],
    verification: {
      apiCheckedAt: new Date().toISOString(),
      githubStars: 58000,
      githubLicense: "AGPL-3.0",
      lastPushAt: new Date().toISOString(),
      source: "https://github.com/immich-app/immich",
    },
  },
  {
    paidTool: {
      name: "Tableau / Looker",
      slug: "tableau",
      category: "Analytics & Business Intelligence",
      pricePerYearUsd: 1020,
      planName: "Creator Seat",
    },
    alternative: {
      name: "Metabase",
      repo: "metabase/metabase",
      language: "Clojure",
      tags: ["bi", "analytics", "sql", "dashboards", "business-intelligence"],
      description: "The easy, open-source way for everyone in your company to ask questions and learn from data without knowing SQL.",
      parity: ["Visual query builder & SQL editor", "Interactive dashboards & drill-downs", "Automated email/Slack pulses & alerts", "Embedding & multi-database connectors (Postgres, Snowflake, BigQuery)"],
      gaps: ["Complex semantic governance layers require Metabase Enterprise"],
      migrationNotes: "Connect Metabase to your SQL database/data warehouse in 5 minutes.",
      platforms: ["docker", "jar", "self-host"],
      license: { spdx: "AGPL-3.0", type: "copyleft" },
      demoUrl: "https://www.metabase.com",
      ecosystems: { docker: "metabase/metabase" },
      screenshots: [{ src: "https://www.metabase.com/images/dashboard.png", alt: "Metabase BI" }],
      tco: { hostingMonthlyEstimateUsd: 10 },
    },
    relationship: "direct",
    goalTags: ["replace-tableau", "bi-dashboards", "data-analytics"],
    verification: {
      apiCheckedAt: new Date().toISOString(),
      githubStars: 41000,
      githubLicense: "AGPL-3.0",
      lastPushAt: new Date().toISOString(),
      source: "https://github.com/metabase/metabase",
    },
  },
  {
    paidTool: {
      name: "Google Analytics 360",
      slug: "google-analytics",
      category: "Analytics & Privacy",
      pricePerYearUsd: 168,
      planName: "Standard",
    },
    alternative: {
      name: "Umami",
      repo: "umami-software/umami",
      language: "TypeScript",
      tags: ["analytics", "privacy", "gdpr", "nextjs", "self-host"],
      description: "Umami is an open source, privacy-focused alternative to Google Analytics. GDPR & CCPA compliant with no cookie banners required.",
      parity: ["Clean real-time dashboard", "No cookie banners or GDPR consent needed", "Event tracking & custom properties", "Lightweight tracking script (< 3KB)"],
      gaps: ["No ad-network remarketing integration"],
      migrationNotes: "Add a single <script> tag to your HTML and disconnect GA4.",
      platforms: ["docker", "self-host", "vercel", "linux"],
      license: { spdx: "MIT", type: "permissive" },
      demoUrl: "https://umami.is",
      ecosystems: { docker: "ghcr.io/umami-software/umami:postgresql-latest" },
      screenshots: [{ src: "https://umami.is/images/dashboard.png", alt: "Umami Analytics" }],
      tco: { hostingMonthlyEstimateUsd: 3 },
    },
    relationship: "direct",
    goalTags: ["replace-google-analytics", "privacy-analytics", "gdpr-compliance"],
    verification: {
      apiCheckedAt: new Date().toISOString(),
      githubStars: 24000,
      githubLicense: "MIT",
      lastPushAt: new Date().toISOString(),
      source: "https://github.com/umami-software/umami",
    },
  },
  {
    paidTool: {
      name: "Streamlabs Ultra / Wirecast",
      slug: "streamlabs-ultra",
      category: "Video & Streaming",
      pricePerYearUsd: 228,
      planName: "Ultra",
    },
    alternative: {
      name: "OBS Studio",
      repo: "obsproject/obs-studio",
      language: "C++",
      tags: ["streaming", "recording", "video", "broadcast", "rtmp"],
      description: "Free and open source software for video recording and live streaming on Windows, Mac or Linux. Low latency and high performance.",
      parity: ["High performance real-time video/audio capturing and mixing", "Unlimited scenes and seamless transitions", "VST audio plugin support & noise suppression", "Multi-platform RTMP/SRT streaming to Twitch, YouTube, Kick"],
      gaps: ["Requires configuring scenes manually without pre-bundled commercial widgets"],
      migrationNotes: "Import scene collections and configure audio output capture.",
      platforms: ["win", "mac", "linux"],
      license: { spdx: "GPL-2.0", type: "copyleft" },
      demoUrl: "https://obsproject.com",
      ecosystems: {},
      screenshots: [{ src: "https://obsproject.com/assets/images/obs_logo.png", alt: "OBS Studio" }],
      tco: { hostingMonthlyEstimateUsd: 0 },
    },
    relationship: "direct",
    goalTags: ["replace-streamlabs-ultra", "live-streaming", "video-production"],
    verification: {
      apiCheckedAt: new Date().toISOString(),
      githubStars: 61000,
      githubLicense: "GPL-2.0",
      lastPushAt: new Date().toISOString(),
      source: "https://github.com/obsproject/obs-studio",
    },
  },
];

export function runExpansion() {
  const raw = JSON.parse(fs.readFileSync(catalogPath, "utf8"));
  const existingRepos = new Set(raw.pairings.map((p) => p.alternative.repo.toLowerCase()));

  let added = 0;
  for (const item of newPairings) {
    if (!existingRepos.has(item.alternative.repo.toLowerCase())) {
      raw.pairings.push(item);
      existingRepos.add(item.alternative.repo.toLowerCase());
      added += 1;
    }
  }

  fs.writeFileSync(catalogPath, JSON.stringify(raw, null, 2), "utf8");
  return { total: raw.pairings.length, added };
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const result = runExpansion();
  console.log(`✓ Catalog expanded! Added ${result.added} new pairings. Total catalog pairings: ${result.total}`);
}
